//DAUD MANZO JUAN PABLO
#include <stdio.h>
#include <stdlib.h>

/*WHILE(1) : ES UNA ESTRUCTURA WHILE QUE ITERA INDEFINIDAMENTE HASTA ENCONTRAR EN ALGUN MOMENTO UN BREAK QUE LA ROMPA.
 * BREAK : ES UN ROMPE ESTRUCTURA ITERATIVA MAS CERCANA, LO PONGO EN UN IF SUPONGAMOS , Y SI HAY UN FOR ABAJO LO ROMPE, LO HACE MIERDA.
 */
int main(void)
{
	return EXIT_SUCCESS;
}
